### ISSUE TITLE
freeBSD to install a linux emulator

### ISSUE THREAD

**Issue by Elimelech** [helloSystem/LinuxRuntime#8]
Can you use your script on regular freeBSD to install a linux emulator?

**Comment by probonopd** [comment]
FreeBSD already comes with the [Linuxulator](https://wiki.freebsd.org/Linuxulator) by default. This image contains a userland (made from Debian ingredients) that can be used by it. 

It is intended for use with helloSystem, but nothing stops you from using it with plain FreeBSD as well.
